import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <Head>
        <title>My page title</title>
      </Head> */}
      <body className="bg-slate-100 w-screen h-screen py-8">
        {children}
        <div id="portal"></div>
      </body>
    </html>
  );
}
